version: '3.3'

services:
  app:
    container_name: 'app'
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 4635:4635
    stdin_open: true
    environment:
      - PORT=4635
    command: npm start
volumes:
  - node_modules
  
