version: '3.3'
services:
  node:
    image: node:alpine
    container_name: app
    restart: always
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 1907:1907
    stdin_open: true
    environment:
      - PORT=1907
    command: npm start

